# Clojure CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.9.7
        command: "/bin/bash"
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "project.clj" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v2-dependencies-{{ checksum "project.clj" }}
      - run:
          name: Install clj-kondo
          command: |
            curl -sLO https://raw.githubusercontent.com/clj-kondo/clj-kondo/master/script/install-clj-kondo
            chmod +x install-clj-kondo
            sudo ./install-clj-kondo
      - run: make lint
      - run: make test
